### PR TITLE
Use the RMG source code instead of binaries for CI

### PR DESCRIPTION
**Pull request by alongd**
Since T3 still requires modifications to both RMG and ARC, for now it requires the updated source code of both repos and not binaries.

### CODE REVIEW

**Comment by kspieks** [comment]
Thanks for the PR! I have two questions:

1. Can you help me understand why this change is necessary? I thought T3's `environment.yml` automatically installed rmg, which is why our documentation discussed installing T3 and ARC, but never RMG explicitly?
2. Is it problematic that these travis checks are failing?

**Comment by alongd** [comment]
I added a few more dependencies.

Since we're using ARC's master branch (with the recent abc change PR) we must use the respective code from RMG, which is currently ony the master branch. RMG's binaries (importing RMG as a library) will only include the recent abc changes once RMG's devs create a new release.

**Comment by kspieks** [comment]
> RMG's binaries (importing RMG as a library) will only include the recent abc changes once RMG's devs create a new release.

"RMG's binaries (importing RMG as a library) will only include the recent abc changes once RMG's devs create a new release." <-- I learn new things every day haha that's good to know thanks for helping me understand the difference

Sure thing. I'll make a branch tonight aimed at updating T3's documentation to explain how the user should download RMG-Py

**Comment by alongd** [comment]
Great, go ahead and merge!

**Pull request merged**
